// Jeu de données de démo (utilisé quand Supabase n'est pas configuré).
// Les valeurs sont représentatives mais pas garanties exactes — pour test UI uniquement.
export const DEMO_VEHICULES = [
  {
    vehicule_id: 'demo-1',
    marque: 'Renault', modele: 'Clio', finition: 'Equilibre',
    energie: 'essence', segment: 'citadine',
    prix_min_eur: 19500, puissance_max_ch: 90,
    conso_mixte: 5.2, conso_elec_mixte: null, co2_g_km: 117,
    critair: '1',
  },
  {
    vehicule_id: 'demo-2',
    marque: 'Peugeot', modele: '208', finition: 'Allure',
    energie: 'essence', segment: 'citadine',
    prix_min_eur: 21800, puissance_max_ch: 100,
    conso_mixte: 5.4, conso_elec_mixte: null, co2_g_km: 122,
    critair: '1',
  },
  {
    vehicule_id: 'demo-3',
    marque: 'Dacia', modele: 'Sandero', finition: 'Essential',
    energie: 'essence', segment: 'citadine',
    prix_min_eur: 13200, puissance_max_ch: 90,
    conso_mixte: 5.6, conso_elec_mixte: null, co2_g_km: 127,
    critair: '1',
  },
  {
    vehicule_id: 'demo-4',
    marque: 'Toyota', modele: 'Yaris', finition: 'Dynamic',
    energie: 'hybride', segment: 'citadine',
    prix_min_eur: 24400, puissance_max_ch: 116,
    conso_mixte: 3.8, conso_elec_mixte: null, co2_g_km: 86,
    critair: '1',
  },
  {
    vehicule_id: 'demo-5',
    marque: 'Renault', modele: 'Clio E-Tech', finition: 'Techno',
    energie: 'hybride', segment: 'citadine',
    prix_min_eur: 25600, puissance_max_ch: 145,
    conso_mixte: 4.1, conso_elec_mixte: null, co2_g_km: 93,
    critair: '1',
  },
  {
    vehicule_id: 'demo-6',
    marque: 'Renault', modele: 'Megane E-Tech', finition: 'Equilibre',
    energie: 'electrique', segment: 'compacte',
    prix_min_eur: 38000, puissance_max_ch: 220,
    conso_mixte: null, conso_elec_mixte: 16.1, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-7',
    marque: 'Tesla', modele: 'Model 3', finition: 'Propulsion',
    energie: 'electrique', segment: 'berline',
    prix_min_eur: 42990, puissance_max_ch: 283,
    conso_mixte: null, conso_elec_mixte: 14.9, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-8',
    marque: 'Peugeot', modele: 'e-208', finition: 'Allure',
    energie: 'electrique', segment: 'citadine',
    prix_min_eur: 35800, puissance_max_ch: 156,
    conso_mixte: null, conso_elec_mixte: 14.7, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-9',
    marque: 'Dacia', modele: 'Spring', finition: 'Expression',
    energie: 'electrique', segment: 'citadine',
    prix_min_eur: 16900, puissance_max_ch: 65,
    conso_mixte: null, conso_elec_mixte: 14.6, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-10',
    marque: 'Citroën', modele: 'C3', finition: 'Plus',
    energie: 'essence', segment: 'citadine',
    prix_min_eur: 14900, puissance_max_ch: 83,
    conso_mixte: 5.3, conso_elec_mixte: null, co2_g_km: 121,
    critair: '1',
  },
  {
    vehicule_id: 'demo-11',
    marque: 'Volkswagen', modele: 'Golf', finition: 'Life',
    energie: 'essence', segment: 'compacte',
    prix_min_eur: 28900, puissance_max_ch: 130,
    conso_mixte: 5.5, conso_elec_mixte: null, co2_g_km: 124,
    critair: '1',
  },
  {
    vehicule_id: 'demo-12',
    marque: 'Volkswagen', modele: 'ID.3', finition: 'Pro',
    energie: 'electrique', segment: 'compacte',
    prix_min_eur: 39990, puissance_max_ch: 204,
    conso_mixte: null, conso_elec_mixte: 15.2, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-13',
    marque: 'Peugeot', modele: '3008', finition: 'Allure',
    energie: 'hybride_rechargeable', segment: 'SUV',
    prix_min_eur: 41500, puissance_max_ch: 225,
    conso_mixte: 1.3, conso_elec_mixte: null, co2_g_km: 30,
    critair: '1',
  },
  {
    vehicule_id: 'demo-14',
    marque: 'BMW', modele: 'Serie 3', finition: '320d',
    energie: 'diesel', segment: 'berline',
    prix_min_eur: 49900, puissance_max_ch: 190,
    conso_mixte: 4.7, conso_elec_mixte: null, co2_g_km: 124,
    critair: '2',
  },
  {
    vehicule_id: 'demo-15',
    marque: 'Toyota', modele: 'C-HR', finition: 'Design',
    energie: 'hybride', segment: 'SUV',
    prix_min_eur: 32400, puissance_max_ch: 140,
    conso_mixte: 4.7, conso_elec_mixte: null, co2_g_km: 105,
    critair: '1',
  },
  {
    vehicule_id: 'demo-16',
    marque: 'Hyundai', modele: 'Kona Electric', finition: 'Intuitive',
    energie: 'electrique', segment: 'SUV',
    prix_min_eur: 37500, puissance_max_ch: 218,
    conso_mixte: null, conso_elec_mixte: 15.3, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-17',
    marque: 'Renault', modele: 'Captur', finition: 'Techno',
    energie: 'essence', segment: 'SUV',
    prix_min_eur: 24900, puissance_max_ch: 90,
    conso_mixte: 5.9, conso_elec_mixte: null, co2_g_km: 134,
    critair: '1',
  },
  {
    vehicule_id: 'demo-18',
    marque: 'Fiat', modele: '500e', finition: 'La Prima',
    energie: 'electrique', segment: 'citadine',
    prix_min_eur: 30400, puissance_max_ch: 118,
    conso_mixte: null, conso_elec_mixte: 14.5, co2_g_km: 0,
    critair: 'E',
  },
  {
    vehicule_id: 'demo-19',
    marque: 'Skoda', modele: 'Octavia', finition: 'Selection',
    energie: 'diesel', segment: 'break',
    prix_min_eur: 32500, puissance_max_ch: 150,
    conso_mixte: 4.6, conso_elec_mixte: null, co2_g_km: 121,
    critair: '2',
  },
  {
    vehicule_id: 'demo-20',
    marque: 'MG', modele: '4', finition: 'Standard',
    energie: 'electrique', segment: 'compacte',
    prix_min_eur: 28990, puissance_max_ch: 170,
    conso_mixte: null, conso_elec_mixte: 16.0, co2_g_km: 0,
    critair: 'E',
  },
]
